name = "prd"
main = "./src/server.js"
compatibility_date = "2024-12-05"
account_id = "e5cf1223aa9b5d7cfdbb3422bd378b41"
#workers_dev = true

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true